In [68]:
import numpy as np
import pandas as pd
data = np.arange(0,30).reshape(6,5)
df = pd.DataFrame(data,index = ["Row 1","Row 2","Row 3","Row 4","Row 5","Row 6"],columns = ["Column 1","Column 2","Column 3","Column 4","Column 5"])
df

       Column 1  Column 2  Column 3  Column 4  Column 5
Row 1         0         1         2         3         4
Row 2         5         6         7         8         9
Row 3        10        11        12        13        14
Row 4        15        16        17        18        19
Row 5        20        21        22        23        24
Row 6        25        26        27        28        29

In [46]:
df.head()   # takes only 1st five values(R,C)

       Column 1  Column 2  Column 3  Column 4  Column 5
Row 1         0         1         2         3         4
Row 2         5         6         7         8         9
Row 3        10        11        12        13        14
Row 4        15        16        17        18        19
Row 5        20        21        22        23        24

In [47]:
df.tail()   #takes last 5 values(R,C) Only

       Column 1  Column 2  Column 3  Column 4  Column 5
Row 2         5         6         7         8         9
Row 3        10        11        12        13        14
Row 4        15        16        17        18        19
Row 5        20        21        22        23        24
Row 6        25        26        27        28        29

In [48]:
type(df)

pandas.core.frame.DataFrame

In [49]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6 entries, Row 1 to Row 6
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Column 1  6 non-null      int64
 1   Column 2  6 non-null      int64
 2   Column 3  6 non-null      int64
 3   Column 4  6 non-null      int64
 4   Column 5  6 non-null      int64
dtypes: int64(5)
memory usage: 460.0+ bytes

In [50]:
df.describe()

        Column 1   Column 2   Column 3   Column 4   Column 5
count   6.000000   6.000000   6.000000   6.000000   6.000000
mean   12.500000  13.500000  14.500000  15.500000  16.500000
std     9.354143   9.354143   9.354143   9.354143   9.354143
min     0.000000   1.000000   2.000000   3.000000   4.000000
25%     6.250000   7.250000   8.250000   9.250000  10.250000
50%    12.500000  13.500000  14.500000  15.500000  16.500000
75%    18.750000  19.750000  20.750000  21.750000  22.750000
max    25.000000  26.000000  27.000000  28.000000  29.000000

In [51]:
df

       Column 1  Column 2  Column 3  Column 4  Column 5
Row 1         0         1         2         3         4
Row 2         5         6         7         8         9
Row 3        10        11        12        13        14
Row 4        15        16        17        18        19
Row 5        20        21        22        23        24
Row 6        25        26        27        28        29

In [18]:
# INDEXING
#1 Column name:-

df["Column 2"]

Row 1     1
Row 2     6
Row 3    11
Row 4    16
Row 5    21
Row 6    26
Name: Column 2, dtype: int64

In [20]:
type(df["Column 2"])  # series since asked for 1 col only

pandas.core.series.Series

In [52]:
#2 Row index:-

df.loc['Row 3']   #Series

Column 1    10
Column 2    11
Column 3    12
Column 4    13
Column 5    14
Name: Row 3, dtype: int64

In [25]:
df.loc[['Row 2','Row 4']]     #dataframe

       Column 1  Column 2  Column 3  Column 4  Column 5
Row 2         5         6         7         8         9
Row 4        15        16        17        18        19

In [69]:
df

       Column 1  Column 2  Column 3  Column 4  Column 5
Row 1         0         1         2         3         4
Row 2         5         6         7         8         9
Row 3        10        11        12        13        14
Row 4        15        16        17        18        19
Row 5        20        21        22        23        24
Row 6        25        26        27        28        29

In [70]:
df > 2

       Column 1  Column 2  Column 3  Column 4  Column 5
Row 1     False     False     False      True      True
Row 2      True      True      True      True      True
Row 3      True      True      True      True      True
Row 4      True      True      True      True      True
Row 5      True      True      True      True      True
Row 6      True      True      True      True      True

In [27]:
# row column index:- we give range for both row and column

df.iloc[1:5,1:4:2]

       Column 2  Column 4
Row 2         6         8
Row 3        11        13
Row 4        16        18
Row 5        21        23

In [29]:
df.iloc[:,1:].values

array([[ 1,  2,  3,  4],
       [ 6,  7,  8,  9],
       [11, 12, 13, 14],
       [16, 17, 18, 19],
       [21, 22, 23, 24],
       [26, 27, 28, 29]])

In [56]:
# Data Operations
data = [
    [25, "IT", 50000, "Mumbai", "Yes"],
    [30, np.nan,60000, "Delhi", "No"],
    [np.nan, "HR", 55000, "Pune", "Yes"],
    [28, "Finance", np.nan, "Bangalore", "No"],
    [35, "IT", 70000, np.nan, "Yes"],
    [40, "Sales", 80000, "Chennai", np.nan]
]

df = pd.DataFrame(
    data,
    index=["Row 1", "Row 2", "Row 3", "Row 4", "Row 5", "Row 6"],
    columns=["Age", "Department", "Salary", "City", "Active"]
)

df    # with table

        Age Department   Salary       City Active
Row 1  25.0         IT  50000.0     Mumbai    Yes
Row 2  30.0        NaN  60000.0      Delhi     No
Row 3   NaN         HR  55000.0       Pune    Yes
Row 4  28.0    Finance      NaN  Bangalore     No
Row 5  35.0         IT  70000.0        NaN    Yes
Row 6  40.0      Sales  80000.0    Chennai    NaN

In [71]:
data = [
    [25, "IT", 50000, "Mumbai", "Yes"],
    [30, np.nan,60000, "Delhi", "No"],
    [np.nan, "HR", 55000, "Pune", "Yes"],
    [28, "Finance", np.nan, "Bangalore", "No"],
    [35, "IT", 70000, np.nan, "Yes"],
    [40, "Sales", 80000, "Chennai", np.nan]
]

df = pd.DataFrame(
    data,
    index=["Row 1", "Row 2", "Row 3", "Row 4", "Row 5", "Row 6"],
    columns=["Age", "Department", "Salary", "City", "Active"]
)

print(df)      # without table

        Age Department   Salary       City Active
Row 1  25.0         IT  50000.0     Mumbai    Yes
Row 2  30.0        NaN  60000.0      Delhi     No
Row 3   NaN         HR  55000.0       Pune    Yes
Row 4  28.0    Finance      NaN  Bangalore     No
Row 5  35.0         IT  70000.0        NaN    Yes
Row 6  40.0      Sales  80000.0    Chennai    NaN

In [58]:
df.isnull().sum()  # Counts null value

Age           1
Department    1
Salary        1
City          1
Active        1
dtype: int64

In [38]:
df.isnull().sum().sum()     # total count of null values

np.int64(5)

In [39]:
df['Department'].value_counts()  # counts the number of occurences of a particular values

Department
IT         2
HR         1
Finance    1
Sales      1
Name: count, dtype: int64

In [40]:
df

        Age Department   Salary       City Active
Row 1  25.0         IT  50000.0     Mumbai    Yes
Row 2  30.0        NaN  60000.0      Delhi     No
Row 3   NaN         HR  55000.0       Pune    Yes
Row 4  28.0    Finance      NaN  Bangalore     No
Row 5  35.0         IT  70000.0        NaN    Yes
Row 6  40.0      Sales  80000.0    Chennai    NaN

In [41]:
df['Age'].unique()  # gives unique values of that particular col or row

array([25., 30., nan, 28., 35., 40.])

In [60]:
# C0NDITIONAL INDEXING

df

        Age Department   Salary       City Active
Row 1  25.0         IT  50000.0     Mumbai    Yes
Row 2  30.0        NaN  60000.0      Delhi     No
Row 3   NaN         HR  55000.0       Pune    Yes
Row 4  28.0    Finance      NaN  Bangalore     No
Row 5  35.0         IT  70000.0        NaN    Yes
Row 6  40.0      Sales  80000.0    Chennai    NaN

In [66]:
df['Age']> 2 # can compare with the previous table

Row 1     True
Row 2     True
Row 3    False
Row 4     True
Row 5     True
Row 6     True
Name: Age, dtype: bool

In [76]:
df[df['Salary']> 58000]     # gives only those values which satisfy the conditions

        Age Department   Salary     City Active
Row 2  30.0        NaN  60000.0    Delhi     No
Row 5  35.0         IT  70000.0      NaN    Yes
Row 6  40.0      Sales  80000.0  Chennai    NaN

In [82]:
# STRING IO and read_csv

from io import StringIO
import pandas as pd
df = pd.read_csv('/content/ecommerce_sales.csv')

In [83]:
df.head()

,Order_ID,Order_Date,Customer_ID,Customer_Name,Age,Gender,City,State,Product_Category,Product_Name,Quantity,Unit_Price,Discount_Percent,Revenue,Cost,Profit,Payment_Method,Customer_Rating,Delivery_Days,Returned
0,ORD1001,05-01-2024,C001,Rahul Sharma,28,Male,Mumbai,Maharashtra,Electronics,Wireless Mouse,2,799,10,1438.20,900,538.20,UPI,4.5,3,No
1,ORD1002,06-01-2024,C002,Priya Patel,35,Female,Ahmedabad,Gujarat,Fashion,Running Shoes,1,2999,15,2549.15,1800,749.15,Credit Card,4.8,5,No
2,ORD1003,07-01-2024,C003,Amit Verma,42,Male,Delhi,Delhi,Home,Air Fryer,1,4999,5,4749.05,3500,1249.05,Debit Card,4.2,4,No
3,ORD1004,08-01-2024,C004,Neha Singh,31,Female,Lucknow,Uttar Pradesh,Beauty,Skin Care Kit,3,999,20,2397.60,1500,897.60,Cash on Delivery,4.1,6,Yes
4,ORD1005,09-01-2024,C005,Vikram Rao,26,Male,Bengaluru,Karnataka,Electronics,Keyboard,2,1499,10,2698.20,1800,898.20,UPI,4.7,2,No

In [84]:
type(df)

pandas.core.frame.DataFrame

In [89]:
pd.read_csv(StringIO(df.to_csv(index=False)))  # to convert stringIo into csv

,Order_ID,Order_Date,Customer_ID,Customer_Name,Age,Gender,City,State,Product_Category,Product_Name,Quantity,Unit_Price,Discount_Percent,Revenue,Cost,Profit,Payment_Method,Customer_Rating,Delivery_Days,Returned
0,ORD1001,05-01-2024,C001,Rahul Sharma,28,Male,Mumbai,Maharashtra,Electronics,Wireless Mouse,2,799,10,1438.20,900,538.20,UPI,4.5,3,No
1,ORD1002,06-01-2024,C002,Priya Patel,35,Female,Ahmedabad,Gujarat,Fashion,Running Shoes,1,2999,15,2549.15,1800,749.15,Credit Card,4.8,5,No
2,ORD1003,07-01-2024,C003,Amit Verma,42,Male,Delhi,Delhi,Home,Air Fryer,1,4999,5,4749.05,3500,1249.05,Debit Card,4.2,4,No
3,ORD1004,08-01-2024,C004,Neha Singh,31,Female,Lucknow,Uttar Pradesh,Beauty,Skin Care Kit,3,999,20,2397.60,1500,897.60,Cash on Delivery,4.1,6,Yes
4,ORD1005,09-01-2024,C005,Vikram Rao,26,Male,Bengaluru,Karnataka,Electronics,Keyboard,2,1499,10,2698.20,1800,898.20,UPI,4.7,2,No
5,ORD1006,10-01-2024,C006,Sneha Iyer,38,Female,Chennai,Tamil Nadu,Books,Python Programming,1,799,0,799.00,300,499.00,Credit Card,4.9,3,No
6,ORD1007,11-01-2024,C007,Arjun Nair,29,Male,Kochi,Kerala,Electronics,Monitor,1,12999,8,11959.08,9500,2459.08,UPI,4.6,4,No
7,ORD1008,12-01-2024,C008,Anjali Gupta,45,Female,Jaipur,Rajasthan,Fashion,Handbag,1,2499,12,2199.12,1500,699.12,Debit Card,4.3,7,No
8,ORD1009,13-01-2024,C009,Karan Mehta,33,Male,Pune,Maharashtra,Home,Vacuum Cleaner,1,6999,10,6299.10,5000,1299.10,Credit Card,4.0,5,Yes
9,ORD1010,14-01-2024,C010,Meera Joshi,27,Female,Indore,Madhya Pradesh,Beauty,Perfume,2,1499,5,2848.10,1800,1048.10,UPI,4.4,3,No
10,ORD1011,15-01-2024,C011,Rohit Kapoor,36,Male,Delhi,Delhi,Electronics,Smart Watch,1,7999,15,6799.15,5000,1799.15,Credit Card,4.8,2,No
11,ORD1012,16-01-2024,C012,Pooja Shah,30,Female,Surat,Gujarat,Fashion,Jacket,1,3499,20,2799.20,2200,599.20,Debit Card,4.2,6,No
12,ORD1013,17-01-2024,C013,Akash Jain,40,Male,Mumbai,Maharashtra,Books,Data Science Handbook,2,999,0,1998.00,800,1198.00,Credit Card,4.9,3,No
13,ORD1014,18-01-2024,C014,Riya Malhotra,24,Female,Chandigarh,Chandigarh,Beauty,Lipstick Set,3,599,10,1617.30,900,717.30,UPI,4.5,4,No
14,ORD1015,19-01-2024,C015,Manish Yadav,32,Male,Patna,Bihar,Home,Mixer Grinder,1,3999,5,3799.05,2800,999.05,Cash on Delivery,4.1,8,Yes
15,ORD1016,20-01-2024,C016,Kavya Reddy,29,Female,Hyderabad,Telangana,Electronics,Headphones,2,2499,10,4498.20,3000,1498.20,Credit Card,4.7,2,No
16,ORD1017,21-01-2024,C017,Sanjay Kumar,37,Male,Kolkata,West Bengal,Home,Water Purifier,1,8999,7,8369.07,6500,1869.07,UPI,4.6,5,No
17,ORD1018,22-01-2024,C018,Divya Menon,34,Female,Kochi,Kerala,Books,Machine Learning Guide,1,1299,0,1299.00,500,799.00,Debit Card,4.8,3,No
18,ORD1019,23-01-2024,C019,Nitin Arora,41,Male,Delhi,Delhi,Fashion,T-Shirt Pack,4,699,15,2376.60,1200,1176.60,UPI,4.0,6,No
19,ORD1020,24-01-2024,C020,Shreya Das,28,Female,Bhubaneswar,Odisha,Beauty,Hair Care Kit,2,1199,10,2158.20,1400,758.20,Credit Card,4.3,4,No

In [90]:
data = ('a,b,c\n'
        '1,2,3\n'
        '4,5,6\n'
        '7,8,9')
type(data)

str

In [91]:
pd.read_csv(StringIO(data))

   a  b  c
0  1  2  3
1  4  5  6
2  7  8  9

In [93]:
pd.read_csv(StringIO(data),usecols = ['b','c'])  # for particular columns only

   b  c
0  2  3
1  5  6
2  8  9

In [98]:
df.to_csv('test.csv')  # gives a structure to the data file

In [100]:
df.to_csv('test.csv',index=False) # removes indexing from the file

In [101]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order_ID          20 non-null     object
 1   Order_Date        20 non-null     object
 2   Customer_ID       20 non-null     object
 3   Customer_Name     20 non-null     object
 4   Age               20 non-null     int64
 5   Gender            20 non-null     object
 6   City              20 non-null     object
 7   State             20 non-null     object
 8   Product_Category  20 non-null     object
 9   Product_Name      20 non-null     object
 10  Quantity          20 non-null     int64
 11  Unit_Price        20 non-null     int64
 12  Discount_Percent  20 non-null     int64
 13  Revenue           20 non-null     float64
 14  Cost              20 non-null     int64
 15  Profit            20 non-null     float64
 16  Payment_Method    20 non-null     object
 17  Customer_Rating   20 non-null     float64
 18  Delivery_Days     20 non-null     int64
 19  Returned          20 non-null     object
dtypes: float64(3), int64(6), object(11)
memory usage: 3.3+ KB

In [102]:
df = pd.read_csv(StringIO(data),dtype='float')     # its a different data file
                                                  # converted all the dtype to particular one only

In [103]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   a       3 non-null      float64
 1   b       3 non-null      float64
 2   c       3 non-null      float64
dtypes: float64(3)
memory usage: 204.0 bytes

In [104]:
df

     a    b    c
0  1.0  2.0  3.0
1  4.0  5.0  6.0
2  7.0  8.0  9.0

In [105]:
df.isnull().sum()

a    0
b    0
c    0
dtype: int64

In [106]:
df['a']

0    1.0
1    4.0
2    7.0
Name: a, dtype: float64

In [116]:
df = pd.read_csv(StringIO(data),dtype={'a': float,'b':int,'c':str})
df

     a  b  c
0  1.0  2  3
1  4.0  5  6
2  7.0  8  9

In [117]:
df.dtypes

a    float64
b      int64
c     object
dtype: object

In [120]:
df = pd.read_csv(StringIO(data),index_col=0)   # removes index col
df

   b  c
a
1  2  3
4  5  6
7  8  9

In [122]:
df = pd.read_csv(StringIO(data),usecols = ['a','b'],index_col=False)  # takes index values and particular col only
df

   a  b
0  1  2
1  4  5
2  7  8

In [125]:
df = pd.read_csv(StringIO(data),usecols = ['a','b'],index_col=0)
df                             # removes index and take particular cols

   b
a
1  2
4  5
7  8